apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spread-service

resources:
  - db-secret.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - cex-futures-engine.yaml

images:
  - name: ghcr.io/sergeyvnec/spread-service/cex-futures-engine
    newTag: sha-43872217007d61021675453e9dc0c394c84c0878
