apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spread-service

resources:
  - db-secret.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - cex-futures-engine.yaml
  - api-server.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sergeyvnec/spread-service/cex-futures-engine
    newTag: sha-a82902ccb575
  - name: ghcr.io/sergeyvnec/spread-service/api-server
    newTag: sha-a82902ccb575
  - name: ghcr.io/sergeyvnec/spread-service/frontend
    newTag: sha-a82902ccb575